-- state/working/schema.sql — GENERATED by scripts/seed_demo_state.py from
-- state/working/migrations/*.sql. Do not hand-edit; add a migration instead.
-- Migrations applied: 001_init, 003_pm_tables, 004_pm_capture_provenance, 005_pm_block_c, 006_gtm_scorecard, 007_content_engine_tables, 008_paid_change_proposals, 009_paid_applied_changes, 010_call_miner_ledger, 011_content_inventory, 012_topic_evidence, 013_pm_g2_create_requested, 014_pm_pulse_delta_cache, 015_textual_ids, 016_mined_meetings_deferred_outcome, 017_mined_meetings_vendor_inbound, 018_topic_backlog_notion_sync, 019_voice_bank_trust_tier

CREATE TABLE "anomalies" (
    id          TEXT    PRIMARY KEY,
    agent       TEXT    NOT NULL,
    detected_at TEXT    NOT NULL,
    surface     TEXT    NOT NULL,
    metric      TEXT    NOT NULL,
    value       REAL,
    baseline    REAL,
    deviation_pct REAL,
    severity    TEXT    NOT NULL CHECK (severity IN ('LOW', 'MED', 'HIGH')),
    description TEXT,
    status      TEXT    NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'acknowledged', 'resolved')),
    resolved_at TEXT,
    created_at  TEXT    NOT NULL
);

CREATE TABLE applied_changes (
    id             INTEGER PRIMARY KEY AUTOINCREMENT,
    agent          TEXT    NOT NULL DEFAULT 'performance-marketer',
    proposal_id    INTEGER NOT NULL,                -- -> paid_change_proposals.id (not enforced)
    approval_ref   TEXT,                            -- greenlight record: decisions/approvals id or Scott->performance-marketer handoff
    platform       TEXT    NOT NULL CHECK (platform IN ('google_ads','linkedin')),
    entity         TEXT    NOT NULL,                -- resource_name acted on
    op_type        TEXT    NOT NULL                 -- 3a allowlist (scripts/paid/config.py)
                           CHECK (op_type IN ('add_negative','set_bid','match_type_promotion','create_experiment')),
    prior_value    TEXT    NOT NULL,                -- JSON snapshot for rollback
    new_value      TEXT    NOT NULL,                -- JSON of the applied state
    mode           TEXT    NOT NULL CHECK (mode IN ('shadow','live')),
    applied_at     TEXT    NOT NULL,                -- ISO 8601
    rolled_back_at TEXT,                            -- ISO 8601; set when reversed
    created_at     TEXT    NOT NULL                 -- ISO 8601
);

CREATE TABLE approvals (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    agent           TEXT    NOT NULL,
    tier            INTEGER NOT NULL CHECK (tier IN (2, 3)),
    draft_type      TEXT    NOT NULL,
    draft_content   TEXT,
    draft_path      TEXT,
    slack_channel   TEXT,
    slack_thread_ts TEXT,
    approver        TEXT,
    approved_at     TEXT,
    status          TEXT    NOT NULL DEFAULT 'pending'
                            CHECK (status IN ('pending', 'approved', 'rejected', 'needs_edit', 'expired')),
    edit_notes      TEXT,
    created_at      TEXT    NOT NULL
);

CREATE TABLE content_briefs (
    id                 INTEGER PRIMARY KEY AUTOINCREMENT,
    agent              TEXT    NOT NULL DEFAULT 'content-producer',
    topic_id           INTEGER,                    -- -> topic_backlog.id (not enforced)
    working_title      TEXT    NOT NULL,
    target_persona     TEXT    NOT NULL DEFAULT 'aaron'
                               CHECK (target_persona IN ('aaron','erin','hannah')),
    tone_code          TEXT,                       -- humor scale A/B/C per channel-tone YAML
    primary_keyword    TEXT,
    secondary_keywords TEXT,                       -- JSON array of strings
    aeo_questions      TEXT,                       -- JSON array of question strings
    word_count_target  INTEGER,
    brief_path         TEXT,                       -- full brief file (state/pending or briefs dir)
    status             TEXT    NOT NULL DEFAULT 'draft'
                               CHECK (status IN ('draft','ready','in_creation','gated',
                                                 'published','killed')),
    created_at         TEXT    NOT NULL            -- ISO 8601
);

CREATE TABLE content_drafts (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    agent           TEXT    NOT NULL DEFAULT 'content-producer',
    brief_id        INTEGER NOT NULL,              -- -> content_briefs.id (not enforced)
    version         INTEGER NOT NULL DEFAULT 1,
    stage           TEXT    NOT NULL DEFAULT 'drafting'
                            CHECK (stage IN ('drafting','voice_edit','humanize','fact_check',
                                             'optimize','scored','gate','passed','no_pass',
                                             'escalated','killed')),
    loop_count      INTEGER NOT NULL DEFAULT 0,    -- pod loops; max 3 then escalate
    revision_cycle  INTEGER NOT NULL DEFAULT 0,    -- gate No Pass cycles; max 2 then back to brief
    rubric_brand    INTEGER,                       -- /10; gate threshold 8 per dimension
    rubric_education INTEGER,                      -- /10
    rubric_evidence INTEGER,                       -- /10
    rubric_human    INTEGER,                       -- /10
    rubric_factual  INTEGER,                       -- /10
    rubric_seo      INTEGER,                       -- /10
    packet_path     TEXT,                          -- review packet in state/pending/
    gate_decision   TEXT    CHECK (gate_decision IN ('pass','no_pass') OR gate_decision IS NULL),
    gate_feedback   TEXT,                          -- structured No Pass feedback (voice/facts/angle/structure)
    published_url   TEXT,                          -- live URL once a human publishes
    created_at      TEXT    NOT NULL,              -- ISO 8601
    updated_at      TEXT                           -- ISO 8601
);

CREATE TABLE content_inventory (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    url           TEXT    NOT NULL UNIQUE,          -- canonical published URL (idempotency key)
    slug          TEXT,
    title         TEXT,
    excerpt       TEXT,                             -- meta description / excerpt
    headings      TEXT,                             -- JSON array of H2/H3s (topic surface for matching)
    primary_topic TEXT,                             -- inferred topic label; reuse voice_bank theme vocab where possible
    persona       TEXT    CHECK (persona IN ('aaron','erin','hannah','unknown') OR persona IS NULL),
    top_queries   TEXT,                             -- JSON array of queries this URL ranks for
    query_source  TEXT    CHECK (query_source IN ('gsc','gsc_csv','ahrefs','none') OR query_source IS NULL),
    published_at  TEXT,                             -- ISO 8601
    last_modified TEXT,                             -- ISO 8601
    source        TEXT    NOT NULL                  -- how this row was populated
                          CHECK (source IN ('crawl','framer','gsc','gsc_csv','ahrefs','content-producer')),
    status        TEXT    NOT NULL DEFAULT 'live'
                          CHECK (status IN ('live','stale','removed')),
    last_seen_at  TEXT,                             -- ISO 8601; refreshed each crawl (detect removed posts)
    created_at    TEXT    NOT NULL                  -- ISO 8601
);

CREATE TABLE decisions (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    agent           TEXT    NOT NULL,
    context         TEXT    NOT NULL,
    decision        TEXT    NOT NULL,
    approved_by     TEXT    NOT NULL DEFAULT 'scott',
    approved_at     TEXT    NOT NULL,
    created_at      TEXT    NOT NULL
);

CREATE TABLE derivative_assets (
    id         INTEGER PRIMARY KEY AUTOINCREMENT,
    agent      TEXT    NOT NULL DEFAULT 'content-producer',
    draft_id   INTEGER NOT NULL,                   -- -> content_drafts.id (not enforced)
    channel    TEXT    NOT NULL CHECK (channel IN ('linkedin','x','newsletter','sales_snippet')),
    asset_path TEXT,                               -- draft file in state/pending/
    status     TEXT    NOT NULL DEFAULT 'draft'
                       CHECK (status IN ('draft','pending_approval','approved','posted','rejected')),
    posted_by  TEXT,                               -- human who posted (never an agent)
    posted_at  TEXT,                               -- ISO 8601
    created_at TEXT    NOT NULL                    -- ISO 8601
);

CREATE TABLE experiments (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    agent           TEXT    NOT NULL DEFAULT 'performance-marketer',
    name            TEXT    NOT NULL,
    platform        TEXT,
    hypothesis      TEXT,
    variant_a       TEXT,
    variant_b       TEXT,
    start_date      TEXT,
    end_date        TEXT,
    status          TEXT    NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'completed', 'cancelled')),
    outcome         TEXT,
    notes           TEXT,
    created_at      TEXT    NOT NULL
);

CREATE TABLE funnel_snapshots (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    agent       TEXT    NOT NULL DEFAULT 'revops-watchdog',
    snapshot_date TEXT  NOT NULL,
    mqls        INTEGER,
    sals        INTEGER,
    sqls        INTEGER,
    pipeline_value REAL,
    mql_to_sal_rate REAL,
    sal_to_sql_rate REAL,
    notes       TEXT,
    created_at  TEXT    NOT NULL
);

CREATE TABLE gtm_scorecard (
    id                 INTEGER PRIMARY KEY AUTOINCREMENT,
    agent              TEXT    NOT NULL,          -- 'revops-watchdog' | 'performance-marketer'
    snapshot_date      TEXT    NOT NULL,          -- YYYY-MM-DD (Friday run date)
    metric             TEXT    NOT NULL,          -- see docs/gtm-scorecard-definitions.md
    period             TEXT    NOT NULL,          -- YYYY-MM
    value              REAL,                      -- actual (complete month) or MTD
    is_complete        INTEGER NOT NULL DEFAULT 0,-- 1 = month closed at snapshot time
    projected          REAL,                      -- projection for incomplete months
    flag               TEXT,                      -- e.g. 'import_polluted', 'low-sample'
    definition_version TEXT    NOT NULL DEFAULT 'v1.0',
    created_at         TEXT    NOT NULL           -- ISO 8601
);

CREATE TABLE "handoffs" (
    id              TEXT    PRIMARY KEY,
    from_agent      TEXT    NOT NULL,
    to_agent        TEXT    NOT NULL,
    subject         TEXT    NOT NULL,
    body            TEXT,
    severity        TEXT    CHECK (severity IN ('LOW', 'MED', 'HIGH')),
    status          TEXT    NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'acknowledged', 'resolved')),
    created_at      TEXT    NOT NULL,
    acknowledged_at TEXT,
    resolved_at     TEXT
);

CREATE TABLE keyword_rankings (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    agent           TEXT    NOT NULL DEFAULT 'performance-marketer',
    snapshot_date   TEXT    NOT NULL,
    keyword         TEXT    NOT NULL,
    position        INTEGER,
    prior_position  INTEGER,
    position_delta  INTEGER,
    search_volume   INTEGER,
    url             TEXT,
    flag            TEXT,
    created_at      TEXT    NOT NULL
);

CREATE TABLE "mined_meetings" (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    agent           TEXT    NOT NULL DEFAULT 'content-researcher',
    meeting_id      TEXT    NOT NULL UNIQUE,
    title_redacted  TEXT,
    meeting_date    TEXT,
    outcome         TEXT    NOT NULL
                            CHECK (outcome IN ('mined','mined_empty','skipped_offtarget','deferred')),
    skip_reason     TEXT,
    call_type       TEXT    CHECK (call_type IN
                            ('prospect_sales','customer','partner_reseller','recruiting',
                             'vendor_inbound','unknown')
                            OR call_type IS NULL),
    icp_persona     TEXT    CHECK (icp_persona IN ('aaron','erin','hannah','unknown')
                            OR icp_persona IS NULL),
    funnel_stage    TEXT    CHECK (funnel_stage IN ('top','mid','bottom') OR funnel_stage IS NULL),
    host            TEXT,
    company_size    TEXT,
    entries_written INTEGER NOT NULL DEFAULT 0,
    packet_id       INTEGER,
    mined_at        TEXT    NOT NULL
);

CREATE TABLE opsos_signals (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    agent           TEXT    NOT NULL DEFAULT 'revops-watchdog',
    check_date      TEXT    NOT NULL,
    new_contacts_7d INTEGER,
    enriched_count  INTEGER,
    coverage_pct    REAL,
    field_coverage_json TEXT,
    flag            TEXT,
    created_at      TEXT    NOT NULL
);

CREATE TABLE paid_change_proposals (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    agent         TEXT    NOT NULL DEFAULT 'performance-marketer',
    dossier_date  TEXT    NOT NULL,                 -- YYYY-MM-DD (the dossier this move belongs to)
    platform      TEXT    NOT NULL CHECK (platform IN ('google_ads','linkedin')),
    campaign_name TEXT,
    bucket        TEXT    NOT NULL                  -- from scripts/paid/classify.py
                          CHECK (bucket IN ('auto_3a','human_3b','creative')),
    op_type       TEXT    NOT NULL                  -- recognized move kinds (classify.py contract)
                          CHECK (op_type IN ('add_negative','set_bid','match_type_promotion',
                                             'create_experiment','pause_ad','budget',
                                             'bid_strategy','cross_channel','creative')),
    summary       TEXT    NOT NULL,                 -- human-readable description of the move
    reason        TEXT,                             -- classifier's rationale for the bucket
    prior_value   TEXT,                             -- JSON snapshot of current state (for execution + rollback)
    target_value  TEXT,                             -- JSON of the proposed new state
    reversal_if   TEXT,                             -- abort condition that should trigger rollback
    linear_ref    TEXT,                             -- creative bucket only: copy-review issue (e.g. MAR-7076)
    approval_id   INTEGER,                          -- -> approvals.id once greenlit (not enforced)
    status        TEXT    NOT NULL DEFAULT 'proposed'
                          CHECK (status IN ('proposed','greenlit','applied',
                                            'awaiting_creative','rejected','rolled_back')),
    decided_at    TEXT,                             -- ISO 8601; set when status leaves 'proposed'
    created_at    TEXT    NOT NULL                  -- ISO 8601
);

CREATE TABLE paid_creative (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    agent           TEXT    NOT NULL DEFAULT 'performance-marketer',
    platform        TEXT    NOT NULL,
    campaign_name   TEXT,
    ad_group        TEXT,
    creative_id     TEXT,
    headline        TEXT,
    description     TEXT,
    impressions     INTEGER,
    clicks          INTEGER,
    ctr             REAL,
    spend           REAL,
    conversions     INTEGER,
    cpl             REAL,
    status          TEXT,
    snapshot_date   TEXT    NOT NULL,
    created_at      TEXT    NOT NULL
);

CREATE TABLE pm_blockers (
    id               INTEGER PRIMARY KEY AUTOINCREMENT,
    agent            TEXT    NOT NULL DEFAULT 'scribe',
    project_id       TEXT,                                -- -> pm_projects.id (not enforced)
    issue_id         TEXT,                                -- -> pm_issues.id (not enforced)
    opened_at        TEXT,                                -- ISO 8601
    resolved_at      TEXT,                                -- ISO 8601
    description      TEXT,
    resolution_notes TEXT,
    created_at       TEXT    NOT NULL,                    -- ISO 8601
    CHECK (project_id IS NOT NULL OR issue_id IS NOT NULL)
);

CREATE TABLE "pm_commitments" (
    id                     INTEGER PRIMARY KEY AUTOINCREMENT,
    agent                  TEXT    NOT NULL DEFAULT 'scribe',
    week_starting          TEXT    NOT NULL,
    owner                  TEXT    NOT NULL,
    commitment             TEXT    NOT NULL,
    linear_link            TEXT,
    linear_ref_type        TEXT    CHECK (linear_ref_type IN ('project','issue')),
    project_id             TEXT,
    issue_id               TEXT,
    resolution             TEXT    CHECK (resolution IN ('by_ref','by_name','confirmed','unresolved')),
    scale                  TEXT    CHECK (scale IN ('project','task','incidental')),
    acknowledged_untracked INTEGER NOT NULL DEFAULT 0,
    nudged_at              TEXT,
    horizon                TEXT    CHECK (horizon IN ('this_week','multi_week')),
    effective_due_date     TEXT,
    completion_status      TEXT    NOT NULL DEFAULT 'pending'
                                   CHECK (completion_status IN ('pending','in_flight','carried','completed','partial','missed','dropped')),
    evaluated_at           TEXT,
    created_at             TEXT    NOT NULL
, create_requested_at TEXT);

CREATE TABLE pm_external_dependencies (
    id                INTEGER PRIMARY KEY AUTOINCREMENT,
    agent             TEXT    NOT NULL DEFAULT 'scribe',
    week_starting     TEXT    NOT NULL,                   -- YYYY-MM-DD
    internal_owner    TEXT    NOT NULL,                   -- marketing team member on the hook
    external_party    TEXT,                               -- agency or partner name
    description       TEXT,
    owner_side_action TEXT,                               -- what we owe to unblock
    expected_delivery TEXT,                               -- YYYY-MM-DD
    linear_link       TEXT,
    status            TEXT    NOT NULL DEFAULT 'pending'
                              CHECK (status IN ('pending','delivered','overdue','cancelled')),
    resolved_at       TEXT,                               -- ISO 8601
    created_at        TEXT    NOT NULL
, raw_text TEXT, parsed_by TEXT
    CHECK (parsed_by IN ('rule', 'model')));

CREATE TABLE pm_issues (
    id                TEXT    PRIMARY KEY,                -- Linear issue ID
    agent             TEXT    NOT NULL DEFAULT 'scribe',
    project_id        TEXT,                               -- -> pm_projects.id (not enforced); NULL for orphans
    title             TEXT    NOT NULL,
    owner             TEXT,                               -- nullable; flagged if missing
    status            TEXT,                               -- raw Linear status
    state             TEXT    CHECK (state IN ('active','stale','blocked','closed')),  -- computed
    due_date          TEXT,                               -- YYYY-MM-DD; nullable
    linear_link       TEXT    NOT NULL,
    short_description TEXT    CHECK (short_description IS NULL OR length(short_description) <= 280),
    last_activity_at  TEXT,                               -- ISO 8601 (from Linear)
    closed_at         TEXT,                               -- ISO 8601
    last_synced_at    TEXT,                               -- ISO 8601; last pulse-check sync
    created_at        TEXT    NOT NULL                    -- ISO 8601 (row creation)
, status_type TEXT);

CREATE TABLE pm_missed_deadlines (
    id                   INTEGER PRIMARY KEY AUTOINCREMENT,
    agent                TEXT    NOT NULL DEFAULT 'scribe',
    project_id           TEXT    NOT NULL,                -- -> pm_projects.id (not enforced)
    original_due_date    TEXT,                            -- YYYY-MM-DD (the missed date)
    detected_at          TEXT,                            -- ISO 8601 (agent noticed the slip)
    prompted_at          TEXT,                            -- ISO 8601 (agent DMed the owner)
    acknowledged_at      TEXT,                            -- ISO 8601 (owner's explanation landed)
    explanation          TEXT,                            -- one-paragraph owner narrative
    linear_comment_link  TEXT,                            -- direct link to the Linear comment
    surfaced_in_thursday INTEGER NOT NULL DEFAULT 0,      -- 0/1 (true if 48h passed without explanation)
    created_at           TEXT    NOT NULL
);

CREATE TABLE pm_projects (
    id                        TEXT    PRIMARY KEY,        -- Linear project ID
    agent                     TEXT    NOT NULL DEFAULT 'scribe',
    name                      TEXT    NOT NULL,
    owner                     TEXT    NOT NULL,           -- marketing team member
    outcome                   TEXT,                       -- GTM Fleet Way: the result being delivered
    quality_bar               TEXT,                       -- GTM Fleet Way: standard not to be compromised
    original_due_date         TEXT,                       -- YYYY-MM-DD; IMMUTABLE once set (no-reschedule rule)
    current_target_date       TEXT,                       -- YYYY-MM-DD; may shift via milestones (communication only)
    health                    TEXT    CHECK (health IN ('on_track','at_risk','off_track')),
    health_source             TEXT    CHECK (health_source IN ('owner','agent_suggested')),
    brief_link                TEXT,                       -- Google Doc URL
    linear_link               TEXT,                       -- Linear project URL
    short_description         TEXT    CHECK (short_description IS NULL OR length(short_description) <= 280),
    closed_at                 TEXT,                       -- ISO 8601
    off_track_acknowledged_at TEXT,                       -- ISO 8601 (GTM Fleet Way off-track playbook step 1)
    off_track_decision        TEXT    CHECK (off_track_decision IN ('recover','reduce_scope','cancel')),
    rca_required              INTEGER NOT NULL DEFAULT 0, -- 0/1
    rca_link                  TEXT,
    last_synced_at            TEXT,                       -- ISO 8601; last pulse-check sync
    created_at                TEXT    NOT NULL            -- ISO 8601 (row creation)
, owner_source TEXT
    CHECK (owner_source IN ('lead','member','external_default','external_declared','unassigned')), status_type TEXT, start_date  TEXT, lead_name   TEXT);

CREATE TABLE pm_rca_log (
    id               INTEGER PRIMARY KEY AUTOINCREMENT,
    agent            TEXT    NOT NULL DEFAULT 'scribe',
    project_id       TEXT,                                -- -> pm_projects.id (not enforced)
    rca_trigger      TEXT,                                -- which RCA trigger fired
    rca_link         TEXT,                                -- URL to the RCA doc (Notion)
    process_changes  TEXT,
    owner_of_changes TEXT,
    created_at       TEXT    NOT NULL                     -- ISO 8601
);

CREATE TABLE pm_standup_responses (
    id                   INTEGER PRIMARY KEY AUTOINCREMENT,
    agent                TEXT    NOT NULL DEFAULT 'scribe',
    week_starting        TEXT    NOT NULL,                -- YYYY-MM-DD
    owner                TEXT    NOT NULL,
    slack_user_id        TEXT,                            -- resolved at capture
    last_week            TEXT,
    this_week            TEXT,
    blockers             TEXT,
    linear_links_present INTEGER NOT NULL DEFAULT 0,      -- 0/1
    responded_at         TEXT,                            -- ISO 8601; NULL until they reply
    created_at           TEXT    NOT NULL, raw_text TEXT, parsed_by TEXT
    CHECK (parsed_by IN ('rule', 'model')),
    UNIQUE (week_starting, owner)
);

CREATE TABLE pm_standup_threads (
    id               INTEGER PRIMARY KEY AUTOINCREMENT,
    agent            TEXT    NOT NULL DEFAULT 'scribe',
    week_starting    TEXT    NOT NULL,                    -- YYYY-MM-DD (Monday)
    channel_id       TEXT    NOT NULL,                    -- resolved #team-marketing id
    master_ts        TEXT    NOT NULL,                    -- Slack ts of the master post (thread anchor)
    master_posted_at TEXT    NOT NULL,                    -- ISO 8601
    sweep_done_at    TEXT,                                -- ISO 8601
    created_at       TEXT    NOT NULL,
    UNIQUE (week_starting)
);

CREATE TABLE research_packets (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    agent         TEXT    NOT NULL DEFAULT 'content-researcher',
    packet_type   TEXT    NOT NULL CHECK (packet_type IN
                          ('social_listening','call_mining','competitor_content')),
    week_starting TEXT    NOT NULL,                -- YYYY-MM-DD (Monday of the run week)
    source_count  INTEGER NOT NULL DEFAULT 0,      -- threads / calls / pages mined
    quiet_week    INTEGER NOT NULL DEFAULT 0,      -- 0/1; explicit "quiet week" flag
    summary       TEXT,                            -- one-paragraph packet summary
    payload_path  TEXT,                            -- file path of the full packet
    created_at    TEXT    NOT NULL                 -- ISO 8601
);

CREATE TABLE schema_migrations (version TEXT PRIMARY KEY, applied_at TEXT NOT NULL);

CREATE TABLE scoring_drift (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    agent           TEXT    NOT NULL DEFAULT 'revops-watchdog',
    snapshot_date   TEXT    NOT NULL,
    median_score    REAL,
    top_decile_count INTEGER,
    top_decile_pct  REAL,
    distribution_json TEXT,
    drift_flag      INTEGER NOT NULL DEFAULT 0,
    drift_note      TEXT,
    created_at      TEXT    NOT NULL
);

CREATE TABLE "spend_alerts" (
    id              TEXT    PRIMARY KEY,
    agent           TEXT    NOT NULL DEFAULT 'performance-marketer',
    detected_at     TEXT    NOT NULL,
    platform        TEXT    NOT NULL,
    campaign_name   TEXT,
    metric          TEXT    NOT NULL,
    value           REAL,
    baseline        REAL,
    deviation_pct   REAL,
    severity        TEXT    NOT NULL CHECK (severity IN ('LOW', 'MED', 'HIGH')),
    description     TEXT,
    status          TEXT    NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'acknowledged', 'resolved')),
    resolved_at     TEXT,
    created_at      TEXT    NOT NULL
);

CREATE TABLE "topic_backlog" (
    id               INTEGER PRIMARY KEY AUTOINCREMENT,
    agent            TEXT    NOT NULL DEFAULT 'content-researcher',
    topic_uid        TEXT    UNIQUE,       -- scripts/ids.py mint; Notion sync key, never edited in Notion
    topic            TEXT    NOT NULL,
    target_persona   TEXT    NOT NULL DEFAULT 'aaron'
                             CHECK (target_persona IN ('aaron','erin','hannah')),
    funnel_stage     TEXT    CHECK (funnel_stage IN ('top','mid','bottom')),
    content_type     TEXT,
    score_total      INTEGER,
    score_icp        INTEGER,
    score_search     INTEGER,
    score_aeo        INTEGER,
    score_evidence   INTEGER,
    score_education  INTEGER,
    evidence_summary TEXT,
    evidence_sources INTEGER NOT NULL DEFAULT 0,
    status           TEXT    NOT NULL DEFAULT 'candidate'
                             CHECK (status IN ('candidate','submitted','approved','rejected',
                                               'needs_edit','briefed','published','refresh')),
    review_notes     TEXT,                 -- Maya's prose, as instruction for next synthesis
    approved_at      TEXT,
    notion_page_id   TEXT,                 -- mirrored Notion page
    notion_synced_at TEXT,                 -- last successful push
    created_at       TEXT    NOT NULL
);

CREATE TABLE topic_evidence (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    topic_id      INTEGER NOT NULL,        -- -> topic_backlog.id (not enforced)
    voice_bank_id INTEGER NOT NULL,        -- -> voice_bank.id (not enforced)
    created_at    TEXT    NOT NULL,        -- ISO 8601
    UNIQUE (topic_id, voice_bank_id)       -- idempotent re-synthesis
);

CREATE TABLE "voice_bank" (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    agent       TEXT    NOT NULL DEFAULT 'content-researcher',
    entry_type  TEXT    NOT NULL CHECK (entry_type IN ('quote','question','pain_point')),
    source      TEXT    NOT NULL CHECK (source IN ('social','sales_call','community')),
    trust_tier  TEXT    NOT NULL CHECK (trust_tier IN ('first_party','attributed','open_ugc')),
    persona     TEXT    CHECK (persona IN ('aaron','erin','hannah','unknown')),
    theme       TEXT,                              -- cluster label
    content     TEXT    NOT NULL,                  -- verbatim text (anonymized for calls)
    source_ref  TEXT,                              -- URL or Grain call reference
    funnel_stage TEXT   CHECK (funnel_stage IN ('top','mid','bottom') OR funnel_stage IS NULL),
    captured_at TEXT,                              -- when the source said it (if known)
    created_at  TEXT    NOT NULL                   -- ISO 8601
);

CREATE TABLE workflow_health (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    agent           TEXT    NOT NULL DEFAULT 'revops-watchdog',
    check_date      TEXT    NOT NULL,
    workflow_id     TEXT    NOT NULL,
    workflow_name   TEXT,
    enrollments_24h INTEGER,
    exits_24h       INTEGER,
    first_step_exit_rate REAL,
    is_active       INTEGER NOT NULL DEFAULT 1,
    flag            TEXT,
    created_at      TEXT    NOT NULL
);

CREATE INDEX idx_gtm_scorecard_lookup
    ON gtm_scorecard (metric, period, snapshot_date);

CREATE INDEX idx_topic_evidence_topic ON topic_evidence (topic_id);
